name: hggzk
description: "hggzk - Hotel & Property Booking App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  # Core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management & DI
  flutter_bloc: ^8.1.6
  get_it: ^7.6.7
  
  # Network
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  web_socket_channel: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.5
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.4
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.1
  firebase_dynamic_links: ^6.0.10
  
  # Location
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Deep Links
  
  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.0
  intl: ^0.20.2
  
  # UI Widgets
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  flutter_rating_bar: ^4.0.1
  timezone: ^0.9.4
  shimmer: ^2.0.0
  google_maps_flutter: ^2.2.3
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.0.0
  visibility_detector: ^0.4.0
  qr_flutter: ^4.1.0
  flutter_staggered_animations: ^1.1.1

  # Navigation
  go_router: ^14.2.7
  app_links: ^6.4.0

  # Added - required by code
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  device_info_plus: ^9.0.0

  flutter_credit_card: ^4.0.1  # For credit card UI
  mask_text_input_formatter: ^2.5.0  # For input formatting
  
  provider: ^6.1.1
  record: ^6.0.0
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  flutter_timezone: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1



flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/payment/
    - assets/icons/

  # أضف الصور الافتراضية في مجلد assets/images/:
  # - default_property.jpg
  # - default_avatar.png